### PR TITLE
Introduce additional permission checks

### PR DESCRIPTION
**Pull request by flupzor**
In the custom views in the Message admin check check if the 'change' permission for the 'Message' model is set in addition to the existing check if for
is_active and is_staff which the django's admin_site.admin_view decorator
introduces.

### CODE REVIEW

**Comment by sastred** [comment]
Hi @flupzor,

Thanks for the pull request. I'm quite busy these days but I will review It as soon as I can.

**Comment by flupzor** [comment]
Thanks for the update :)

**Comment by sastred** [comment]
Hello @flupzor,

I have reviewed your pull request and despite of it can be useful for your particular use case, I think it is not appropiate for general use: you are trying to required change permissions to views that are read only.

Anyway, thanks for trying to improve django yubin.

Best regards.

**Comment by flupzor** [comment]
Yeah, it's too bad that we don't have a 'read' permission in Django. Thanks for looking at the PR.

**Pull request closed without merging**
